# Generated by Django 6.0.5 on 2026-05-26 04:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tital', models.CharField(max_length=50)),
                ('author', models.CharField(max_length=50)),
                ('genre', models.CharField(choices=[('Fiction', 'Fiction'), ('Non-Fiction', 'Non-Fiction'), ('Science', 'Science'), ('History', 'History'), ('Technology', 'Technology'), ('Biography', 'Biography'), ('Education', 'Education'), ('Comics', 'Comics')], max_length=50)),
                ('publication_year', models.DateField(auto_now_add=True)),
            ],
        ),
    ]
