# Generated by Django 6.0.5 on 2026-05-26 04:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='book',
            old_name='tital',
            new_name='title',
        ),
    ]
